# Generated by Django 3.1.2 on 2020-10-17 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('name', models.CharField(max_length=17)),
                ('password', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('cname', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vname', models.CharField(max_length=200)),
                ('vurl', models.URLField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecourse.courses')),
            ],
        ),
    ]
