# Generated by Django 3.1.2 on 2020-10-17 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecourse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameofcmt', models.CharField(max_length=20)),
                ('cmt', models.CharField(max_length=200)),
                ('vid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecourse.videos')),
            ],
        ),
    ]
