# Generated by Django 3.1.2 on 2020-10-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecourse', '0002_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='vno',
            field=models.IntegerField(default=1),
        ),
    ]
